# Generated by Django 3.0 on 2020-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_password_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='author',
        ),
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
