# Generated by Django 3.0 on 2020-09-07 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('topic', models.CharField(choices=[('Philosophy', 'Philosophy'), ('Fitness', 'Fitness'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Politics', 'Politics'), ('Others', 'Others')], max_length=20)),
                ('image', models.ImageField(default='SOME STRING', upload_to='')),
            ],
        ),
    ]
