# Generated by Django 3.0 on 2020-09-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('General', 'General'), ('Academics', 'Academics'), ('Sports', 'Sports'), ('Lifestyle', 'Lifestyle'), ('Events', 'Events'), ('Others', 'Others')], max_length=20),
        ),
    ]
