# Generated by Django 3.0 on 2020-09-13 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200913_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
