# Generated by Django 3.0 on 2020-09-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_announcements_date_posted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
